global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'stoockermt-api'
    static_configs:
      - targets: ['stoockermt-api:80']
    metrics_path: '/metrics'

  - job_name: 'sql-server'
    static_configs:
      - targets: ['sqlserver:1433']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'alerts.yml'

# Alerts configuration
alerts.yml: |
  groups:
    - name: stoockermt
      interval: 30s
      rules:
        - alert: HighErrorRate
          expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High error rate detected"
            description: "Error rate is above 5% for 5 minutes"
        
        - alert: HighResponseTime
          expr: histogram_quantile(0.95, http_request_duration_seconds_bucket) > 0.5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High response time"
            description: "95th percentile response time is above 500ms"
        
        - alert: DatabaseConnectionFailure
          expr: sql_server_up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Database connection failed"
            description: "Cannot connect to SQL Server"